version: '3.8'

services:
  mongodb:
    image: mongo:6.0
    container_name: flowbit-mongodb
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password123
      MONGO_INITDB_DATABASE: flowbit
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - flowbit-network

  redis:
    image: redis:7-alpine
    container_name: flowbit-redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - flowbit-network

volumes:
  mongodb_data:
  redis_data:

networks:
  flowbit-network:
    driver: bridge 